---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  immutable: true

components:
  - ./../../base/transformers

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/secrets.yaml
  - resources/storage.yaml
