---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

generatorOptions:
  immutable: true

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/configmap.yaml
  - resources/secrets.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/ingress.yaml
  - resources/hpa.yaml

images:
  - name: registry.hadenlabs.com/toolkit/whoami
    newName: registry.hadenlabs.com/toolkit/whoami
    newTag: latest
