apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress

helmCharts:
  - name: nginx-ingress-controller
    repo: https://charts.bitnami.com/bitnami
    version: "11.0.0"
    releaseName: nginx-ingress-controller
    namespace: nginx-ingress
    valuesFile: values/nginx.yaml
    includeCRDs: true

commonAnnotations:
  meta.helm.sh/release-name: nginx-ingress
  meta.helm.sh/release-namespace: nginx-ingress
commonLabels:
  app.kubernetes.io/managed-by: Helm
