---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

generatorOptions:
  immutable: true

components:
  - ./../../../../base/

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/namespace.yaml
  - resources/configmap.yaml
  - resources/secrets.yaml
