apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.11.3
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: values/nginx.yaml
    includeCRDs: true

commonAnnotations:
  meta.helm.sh/release-name: ingress-nginx
  meta.helm.sh/release-namespace: ingress-nginx
