---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server

generatorOptions:
  immutable: true

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/namespace.yaml
  - resources/secrets.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/hpa.yaml
  # - resources/service-monitor.yaml
  - resources/helm
  - resources/ingress.yaml
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
# patches:
#   - path: patches/update-resources.yaml
#     target:
#       group: apps
#       kind: Deployment
#       name: prod-ingress-nginx-controller
#       namespace: metrics-server
#       version: v1
#   - path: patches/remove-replicas.yaml
#     target:
#       group: apps
#       kind: Deployment
#       name: prod-ingress-nginx-controller
#       namespace: metrics-server
#       version: v1
