---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress

generatorOptions:
  immutable: true

components:
  - ../../../../base

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/namespace.yaml
  - resources/secrets.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/hpa.yaml
  - resources/helm
  - resources/ingress.yaml
# patches:
#   - path: patches/deployment-nginx-ingress-controller.yaml
#     target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: nginx-ingress-controller
