apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.0 # https://artifacthub.io/packages/helm/metrics-server/metrics-server?modal=changelog
    releaseName: metrics-server
    namespace: metrics-server
    includeCRDs: true
    valuesFile: values/metrics-server.yaml

commonAnnotations:
  meta.helm.sh/release-name: metrics-server
  meta.helm.sh/release-namespace: metrics-server
commonLabels:
  app.kubernetes.io/managed-by: Helm
