---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: architecture@hadenlabs.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key-staging
    solvers:
      - http01:
          ingress:
            # ingressClassName: nginx
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: architecture@hadenlabs.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
      - http01:
          ingress:
            # ingressClassName: nginx
            class: nginx
            # podTemplate:
            #   spec:
            #     nodeSelector:
            #       "kubernetes.io/os": linux
            #apiVersion: cert-manager.io/v1
