---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: whoami-logs
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /nfs/whoami/logs
    type: DirectoryOrCreate
---

