apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-db
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /srv/kind/core/default/db
    type: DirectoryOrCreate
