---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-db
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: default-db
