---
apiVersion: v1
kind: Secret
metadata:
  name: default-postgresql
type: Opaque
data:
  postgres_admin_password: SFpQaUVrTkg3RXgyaw==
  postgres_replication_password: TkVVNE1GZDVMY21qeQ==
  postgres_user_password: cThVTThpRG9IUVNvSA==
  postgres_host: ZGVmYXVsdC5wb3N0Z3Jlc3FsLnN2Yy5jbHVzdGVyLmxvY2Fs
  postgres_port: NTQzMg==
  postgres_user: dXNlcl9kZWZhdWx0
  postgres_database: ZGVmYXVsdA==
