kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-base
networking:
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
  podSubnet: "192.168.0.0/16"
  disableDefaultCNI: true
nodes:
  - role: control-plane
    image: kindest/node:v1.26.14
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /Volumes/Data/kind
        containerPath: /srv/kind
        readOnly: false
        selinuxRelabel: false

    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
        protocol: TCP # Optional, defaults to tcp
      - containerPort: 443
        hostPort: 3443
  - role: worker
    image: kindest/node:v1.26.14
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "worker1=true"
  - role: worker
    image: kindest/node:v1.26.14
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "worker2=true"
---
kind: ImageContentSourcePolicy
apiVersion: policy/v1alpha1
metadata:
  name: allow-all
spec:
  repositories:
    - name: "*"
      policy:
        rules:
          - when:
              - tag: "*"
            then:
              - allow: true
