kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: calico
networking:
  disableDefaultCNI: false
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.245.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.30.8
    # Necessary to explore port
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: ~/Data/kind
        containerPath: /srv/kind
        readOnly: false
        selinuxRelabel: false

    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: TCP # Optional, defaults to tcp
      - containerPort: 443
        hostPort: 443
  - role: worker
    image: kindest/node:v1.30.8
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "worker1=true"
    extraMounts:
      - hostPath: ~/Data/kind
        containerPath: /srv/kind
        readOnly: false
        selinuxRelabel: false

# kubeadmConfigPatches:
#   - |
#     apiVersion: kubeadm.k8s.io/v1beta2
#     kind: ClusterConfiguration
#     metadata:
#       name: config
#     networking:
#       podSubnet: "192.168.0.0/16"
#       serviceSubnet: "10.245.0.0/16"
---
kind: ImageContentSourcePolicy
apiVersion: policy/v1alpha1
metadata:
  name: allow-all
spec:
  repositories:
    - name: "*"
      policy:
        rules:
          - when:
              - tag: "*"
            then:
              - allow: true
