apiVersion: builtin
kind: LabelTransformer
metadata:
  name: BaseLabelsTransformer
labels:
  app.kubernetes.io/metadata.name: base
  app.kubernetes.io/name: base
  app.kubernetes.io/component: base
  app.kubernetes.io/part-of: base
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/stage: local
  app.kubernetes.io/owner: hadenlabs

fieldSpecs:
  - path: metadata/labels
    create: true

  - kind: Certificate
    path: spec/secretTemplate/labels
    create: true

  - kind: CronJob
    path: spec/jobTemplate/metadata/labels
    create: true

  - kind: CronJob
    path: spec/jobTemplate/spec/template/metadata/labels
    create: true

  - kind: DaemonSet
    path: spec/template/metadata/labels
    create: true

  - kind: DaemonSet
    path: spec/selector/matchLabels
    create: true

  - kind: Deployment
    path: spec/template/metadata/labels
    create: true

  - kind: Deployment
    path: spec/selector/matchLabels
    create: true

  - kind: PersistentVolumeClaim
    path: spec/selector/matchLabels
    create: true

  - kind: Service
    path: spec/selector
    create: true

  - kind: ServiceMonitor
    path: spec/selector/matchLabels
    create: true

  - kind: StatefulSet
    path: spec/template/metadata/labels
    create: true

  - kind: StatefulSet
    path: spec/selector/matchLabels
    create: true
