---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

generatorOptions:
  immutable: true

components:
  - ./../../../../../../base/transformers
  - ./../../../../../base/transformers

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/secrets.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/clusterissuer.yaml
