---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

components:
  - ../../../../base/transformers

generatorOptions:
  immutable: true

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/secrets.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/configmap.yaml
