apiVersion: builtin
kind: LabelTransformer
metadata:
  name: commonLabelsTransformer
labels:
  app.kubernetes.io/metadata.name: cluster-issuer
  app.kubernetes.io/kustomize.name: cluster-issuer
  app.kubernetes.io/component: cert-manager

fieldSpecs:
  - path: metadata/labels
    create: true

  - kind: Certificate
    path: spec/secretTemplate/labels
    create: true

  - kind: CronJob
    path: spec/jobTemplate/metadata/labels
    create: true

  - kind: CronJob
    path: spec/jobTemplate/spec/template/metadata/labels
    create: true

  - kind: DaemonSet
    path: spec/template/metadata/labels
    create: true

  - kind: DaemonSet
    path: spec/selector/matchLabels
    create: true

  - kind: Deployment
    path: spec/template/metadata/labels
    create: true

  - kind: Deployment
    path: spec/selector/matchLabels
    create: true

  - kind: PersistentVolumeClaim
    path: spec/selector/matchLabels
    create: true

  - kind: Secrets
    path: spec/template/metadata/labels
    create: true

  - kind: Secrets
    path: spec/selector/matchLabels
    create: true

  - kind: Service
    path: spec/selector
    create: true

  - kind: ServiceMonitor
    path: spec/selector/matchLabels
    create: true

  - kind: StatefulSet
    path: spec/template/metadata/labels
    create: true

  - kind: StatefulSet
    path: spec/selector/matchLabels
    create: true
