---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis

generatorOptions:
  immutable: true

components:
  - ../../../../../base/transformers

transformers:
  - transformers/label.yaml
  - transformers/annotation.yaml

resources:
  - resources/configmap.yaml
  - resources/secrets.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/ingress.yaml
  - resources/hpa.yaml

images:
  - name: redis:latest
    newName: redis
    newTag: 7.2-alpine
